[package]
name = "db"
version = "0.1.0"
edition.workspace = true

[dependencies]
types.workspace = true
bytes.workspace = true
chrono.workspace = true
nix.workspace = true
libc.workspace = true
crossbeam-channel.workspace = true
